### ISSUE TITLE
[Linux] Dolphin's "Hidden Files" icon, KDE Plasma

### ISSUE THREAD

**Issue by bugworm** [Nitrux/luv-icon-theme#168]
![screenshot_20161125_102450](https://cloud.githubusercontent.com/assets/7214361/20618824/e747db42-b2f9-11e6-85a7-0340c5eff42d.png)

**Comment by paulovr** [comment]
The problem continues with the lack of icon.

**Comment by UriHerrera** [comment]
Icons added.
