### ISSUE TITLE
[Linux] Unity

### ISSUE THREAD

**Issue by codingkapoor** [Nitrux/luv-icon-theme#170]
Volume & Power button icons are missing in the notification bar in the Ubuntu 16.04.
![missing icons](https://cloud.githubusercontent.com/assets/4599890/22180347/a928513a-e093-11e6-871d-35b0864e93d0.png)

**Comment by UriHerrera** [comment]
I'm going to close this issue and reference it here https://github.com/Nitrux/luv-icon-theme/issues/188 since it's about the same problem.
