### ISSUE TITLE
[Linux] Missing 'stop loading' icon

### ISSUE THREAD

**Issue by demoy** [Nitrux/luv-icon-theme#171]
The stop loading icon [used in browsers and filemangers] seems to be missing

1. Below Reload Icon (before click)
![screenshot_20170211_100753](https://cloud.githubusercontent.com/assets/2396524/22854680/30d069d4-f042-11e6-926f-e27c441d990c.png)

2. Below Missing Icon (while loading)
![screenshot_20170211_100722](https://cloud.githubusercontent.com/assets/2396524/22854681/30d29d12-f042-11e6-964a-31fad54a7016.png)

**Comment by UriHerrera** [comment]
Icon added.
