### ISSUE TITLE
[Linux] Plasma 5 missing icons

### ISSUE THREAD

**Issue by romanlex** [Nitrux/luv-icon-theme#172]
Missing icons on system (((
![image](https://cloud.githubusercontent.com/assets/3369304/23183829/73990718-f88e-11e6-9f8f-9eb772b825ea.png)
![image](https://cloud.githubusercontent.com/assets/3369304/23183875/8e4d9b82-f88e-11e6-8201-440f7e4d8c35.png)

And missing app icons, example KSystemLog

**Comment by UriHerrera** [comment]
Icons added.
