### ISSUE TITLE
[Linux] Otter Browser

### ISSUE THREAD

**Issue by m4sk1n** [Nitrux/luv-icon-theme#173]
- [Otter Browser](https://github.com/OtterBrowser/otter-browser)
- Project that aims to recreate the best aspects of the classic Opera (12.x) UI using Qt5
- `Icon=otter-browser`
![10384419](https://cloud.githubusercontent.com/assets/21127288/24331347/a9788aa8-1232-11e7-8fb7-64e8a82c698e.png)

**Comment by UriHerrera** [comment]
Can't download the browser form their links. No mirrors are found. Reopen when links are available.

![image](https://user-images.githubusercontent.com/3053525/36408997-61698e42-15ce-11e8-8df2-af3ed2291d7c.png)
