### ISSUE TITLE
[Linux] Missing icons

### ISSUE THREAD

**Issue by Vintodrimmer** [Nitrux/luv-icon-theme#178]
Good day,

I'm not sure that it is exactly the problem with the missing icons, but I hope the screenshots will make the issue clear.

Icons are misalligned in the `firefox` filepicker.
![gtk-filepicker firefox](https://raw.githubusercontent.com/Vintodrimmer/docs/master/filepicker.png)

`Lxappearance` shows missing icons and reverts to default ones in some places.
![lxappearance](https://raw.githubusercontent.com/Vintodrimmer/docs/master/lxappearance.png)

There is a missing icon in the `firefox` closing dialogue.
![firefox close dialogue](https://raw.githubusercontent.com/Vintodrimmer/docs/master/firefox.png)

Some icons, such as 'home' and 'bookmarks' revert to the default ones.
![spacefm](https://raw.githubusercontent.com/Vintodrimmer/docs/master/spacefm.png)

Same in the 'rename' dialogue in spacefm.
![spacefm rename](https://raw.githubusercontent.com/Vintodrimmer/docs/master/rename_spacefm.png)

And the last one is the missing `connman-gtk-ui` icon. It is basically an applet that shows the connection status.
![connman-gtk-ui](https://github.com/Vintodrimmer/docs/blob/master/2017-07-28-10:12:45-screenshot.png)

My question is are all the shown icons missing or is there something I'm doing wrong? I only have `gtk` apps so I copied the `Luv` folder to the `~/.icons` and used `lxappearance` to apply the theme.

**Comment by UriHerrera** [comment]
What distribution are you using? I assume that's LXDE?.

**Comment by Vintodrimmer** [comment]
Distribution is Void Linux.

WM is bspwm.

There is no DE but I find lxappearance to be the most reliable way to set both gtk2 and gtk3 themes. (at least until now)

**Comment by unc926** [comment]
**have same problem Gnome 3.24**

I've fixed some parts, but in many places I have the same problem.

![2017-07-29 18-15-50 ekran goruntusu](https://user-images.githubusercontent.com/30185386/28745872-2e3eaccc-748a-11e7-97f0-354cdb95a56a.png)

**Comment by UriHerrera** [comment]
I'm going to close this issue and reference it here https://github.com/Nitrux/luv-icon-theme/issues/188 since it's about the same problem.
