### ISSUE TITLE
new firefox nightly icon

### ISSUE THREAD

**Issue by pawanyadav** [Nitrux/luv-icon-theme#179]
please add new firefox nightly icon
https://pbs.twimg.com/profile_images/893734506766761984/0zPXpdIS.jpg

**Comment by pawanyadav** [comment]
official announcement is here 
https://twitter.com/FirefoxNightly/status/893577526009880576

**Comment by UriHerrera** [comment]
Please follow the guidelines in the README to report icons. Closed until updated.
