### ISSUE TITLE
How to move to /usr/share

### ISSUE THREAD

**Issue by ImreZehl** [Nitrux/luv-icon-theme#180]
Hello I'm quite new to Linux and to the command line. I installed successfully but can't move the theme, which is now in my desktop, to the share folder because I need permission.
Any easy way to do it?

**Comment by luis-lavaire** [comment]
@ImreZehl, don't move it to /usr, just create a folder in your home directory called `.icons` and place the icons over there. This are the steps:

- Open a terminal window.
- Type `mkdir -p .icons`.
- Extract the contents of the zip file to `.icons`.

BTW, why you don't install the icons using your package manager? That would be far easier.

**Comment by ImreZehl** [comment]
Well I still can't figure it out.
I copied your command into the terminal but it didn't do anything. 
Then I looked into the package manager but I don't know how to use it either :laughing:

**Comment by luis-lavaire** [comment]
Which distribution are you using?

**Comment by ImreZehl** [comment]
I have Linux Mint 18.2 with the cinnamon desktop.

**Comment by UriHerrera** [comment]
* Download the [icons](https://github.com/Nitrux/luv-icon-theme/archive/master.zip) and extract the zip.
* Open terminal window and navigate to the directory where you extracted the zip.
* Copy the folders to `/usr/share/icons`, use: `sudo cp Luv/ /usr/share/icons`
