### ISSUE TITLE
Have some broken .svg files

### ISSUE THREAD

**Issue by unc926** [Nitrux/luv-icon-theme#181]
hi, some icon files appear to be corrupt and unusable.

![screenshot_20171101_232241](https://user-images.githubusercontent.com/30185386/32296573-a0dd8c76-bf5d-11e7-9575-cc6f66f1211f.png)

I checked all folders. Too many corrupted icon files.

![screenshot_20171101_231812](https://user-images.githubusercontent.com/30185386/32296851-6ead0fb4-bf5e-11e7-9d6e-6c674967f931.png)

corrupt .svg files are available in almost all folders. all of them need to be corrected.

**Comment by UriHerrera** [comment]
I just checked, none are broken, clone the git repo instead of downloading the zip.

**Comment by unc926** [comment]
I downloaded it again with git. everything is OK. Thank you.
