### ISSUE TITLE
[Linux] UI Icons for Babe QML

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/luv-icon-theme#184]
Babe QML with Luv:

![image](https://user-images.githubusercontent.com/3053525/36401091-bc0dfe52-159a-11e8-81d4-4a85d30177bf.png)

Babe QML with Breeze:

![image](https://user-images.githubusercontent.com/3053525/36401111-d99b32fa-159a-11e8-84a3-df082b02978b.png)

````
toolbar:
headphones => headphones (symbolic like) *
filename-filetype-amarok => view-media-track
media-album-cover => view-media-album-cover
view-media-artist [done]
view-media-playlist [done]
games-config-options => view-media-config *

headers:
window-close [needs fixing]
player-time (??) => media-playlist-play [missing]
archive-insert (??) => media-playlist-append [missing]
overflow-menu [good]

playback bar:
documentinfo [good]
love [good]
media-skip-backward [good]
media-playback-start [good]
media-playback-pause [good]
media-skip-forward [good]
media-playlist-shuffle [good]
media-playlist-repeat [good]
media-playlist-normal [missing]

playlists:
amarok_playcount => view-media-playcount *
draw-star => view-media-favorite *
filename-year-amarok => view-media-recent *
love [good]
internet-services [good]
tag [good]
similarartists-amarok => view-media-similarartists *
office-chart-line => view-media-chart *
filename-track-amarok => view-media-genre [missing] *
````

**Comment by DarkknightAK** [comment]
Hi Uri,

thanks for the e-mail

added the needed icons to breeze in 22px 16 and 32px will follow later
https://cgit.kde.org/breeze-icons.git/commit/?id=f82020757e563c2dacc21d0df4989490a11c79d9

**Comment by milohr** [comment]
Still missing star icon for rating 
draw-star

![screenshot_20180301_104836](https://user-images.githubusercontent.com/5911329/36854101-2801e024-1d3e-11e8-9594-a7351d4c9c91.png)
![screenshot_20180301_104804](https://user-images.githubusercontent.com/5911329/36854102-283c6168-1d3e-11e8-928e-55ca1d7bee8a.png)

**Comment by milohr** [comment]
I recently added the option to watch youtube video on the app, and there's missing a video icon
![screenshot_20180307_120938](https://user-images.githubusercontent.com/5911329/37106684-737553f8-2200-11e8-816e-598013b4dd1c.png)

![screenshot_20180307_114716](https://user-images.githubusercontent.com/5911329/37106686-73a51480-2200-11e8-877d-8bb36d685a73.png)

**Comment by DarkknightAK** [comment]
Icon name please

**Comment by milohr** [comment]
view-media-video
in order to follow the other icon name conventions, currently i'm using videoclip-amarok

**Comment by milohr** [comment]
There's symblinks missing:
album -> view-media-album
amarok-artist -> view-media-artist
