### ISSUE TITLE
[Linux] Plasma, fcitx icon missing 

### ISSUE THREAD

**Issue by ICHx** [Nitrux/luv-icon-theme#185]
![image](https://user-images.githubusercontent.com/11556527/37250540-8302b5ee-253a-11e8-8570-a0bca5832c6e.png)
I really like this theme so I would like to raise the issue using it. :smile: 

On the bottom left, the “often use” icon is blank, and on the bottom right, the blank between steam and volume is ”fcitx keyboard“

Distro: Manjaro x64 rolling
Package: luv-icon-theme from aur

**Comment by UriHerrera** [comment]
Plasma is loading the icon from the icon theme however it should load its icons from the Plasma theme currently in use but you're right, the icon is missing in the menu.
