### ISSUE TITLE
[Linux/Android] Action icons colouring and consistency

### ISSUE THREAD

**Issue by milohr** [Nitrux/luv-icon-theme#197]
The icon for activating the multiple selection changes its shape:
"edit-select"
![image 5](https://user-images.githubusercontent.com/5911329/48090563-4bc0a480-e1d5-11e8-93fe-f16b704dfd25.png)
![image 4](https://user-images.githubusercontent.com/5911329/48090564-4bc0a480-e1d5-11e8-98df-731951e86374.png)

The "view-preview" icon doesn't get colored like the other"symbolic" looking action icons.
This happens only on Android, on GNU Linux works fine.
![image 3](https://user-images.githubusercontent.com/5911329/48090565-4bc0a480-e1d5-11e8-8b92-5fb6916de151.png)

**Comment by UriHerrera** [comment]
`edit-select` changes because of the icon in size 32px for Krunner and the Plasma settings dialogs. Index should probably use another image for example `item-select` which would be a symlink to the 22px version.

Same with `view-preview`.

**Comment by UriHerrera** [comment]
Added `image-preview` a symlink to `/actions/22/view-preview` and `item-select` a symlink to  `/actions/22/edit-select`
