### ISSUE TITLE
Broken on LXQT

### ISSUE THREAD

**Issue by Serkan-devel** [Nitrux/luv-icon-theme#198]
![2018-11-27-184810_1366x768_scrot](https://user-images.githubusercontent.com/16866642/49100960-65ee1f80-f275-11e8-8de2-847dda977a00.png)

**Comment by UriHerrera** [comment]
Please read the issue guidelines on how to properly create a new issue. Thanks.

-----

I'm not sure why you say the icon theme is broken?. Besides the missing icons for the Firefox versions in your screenshot, I can only see that the panel is using the monochrome images, but this is not a bug.

LXQt does not use CSS coloring like Plasma 5 does and like similar to what Gnome 3 does as well to color these icons, so this means that this is a missing feature of LXQt not a bug in the icon theme.
