### ISSUE TITLE
[Linux] Network tray icons (nm-applet) missing

### ISSUE THREAD

**Issue by primetoxinz** [Nitrux/luv-icon-theme#200]
**Describe the bug**
Icons for nm-applet and possibly other networking tray icons are missing 
 *Desktop (please complete the following information):**
 - OS: Archlinux, i3wm

Pictures while using Luv (Adwaita defaults)

![Normal Ethernet](https://user-images.githubusercontent.com/4721642/53376721-58f0d300-392d-11e9-8f46-e4b165e38c72.png) - Normal Ethernet
![Offine](https://user-images.githubusercontent.com/4721642/53376847-c3a20e80-392d-11e9-8486-c653d704ddea.png) - Offline
![VPN](https://user-images.githubusercontent.com/4721642/53376698-50989800-392d-11e9-823e-bf612ff7bf0c.png) - VPN
There are more states this tray can be in but I can't get pictures of them 

Some of the icon paths:
```
/usr/share/icons/Adwaita/./scalable/status/network-wired-disconnected-symbolic.svg
/usr/share/icons/Adwaita//scalable/status/network-wired-no-route-symbolic.svg
/usr/share/icons/Adwaita/scalable/status/network-wired-offline-symbolic.svg
/usr/share/icons/Adwaita/scalable/status/network-wired-acquiring-symbolic.svg
```

**Comment by UriHerrera** [comment]
I'm going to close this issue and reference it here https://github.com/Nitrux/luv-icon-theme/issues/188 since it's about the same problem.
