### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by xeux** [Nitrux/luv-icon-theme#204]
I also love the icons, some missing are:

Thunderbird
LibreOffice
Rhythmbox
Files (Gnome)

**Comment by UriHerrera** [comment]
Please add the relevant information to your issue. Thanks.

**Comment by xeux** [comment]
I think all Gnome icons are not supported for example: gnome-fs-directory.png

**Comment by UriHerrera** [comment]
Closing as per the [FAQ](https://github.com/Nitrux/luv-icon-theme/wiki/L%C3%BCv-FAQ#creating-new-issues).

> Issues must have all of the information listed in the README. If your problem doesn't have all the info required, it won't be fixed.
