### ISSUE TITLE
Missing symblinks for Maui apps

### ISSUE THREAD

**Issue by milohr** [Nitrux/luv-icon-theme#207]
To make the icons show on PlaMo with breeze and on Android with Luv, there are missing symlinks to the names the Breeze icon theme uses.

so far:

for Buho:
view-pim-notes -> view-notes
view-pim-news -> view-links
view-pim-journal -> view-books
pin -> edit-pin

**Comment by milohr** [comment]
for Nota:
editor -> document-edit??? (icon for getting to the editor view)
view-pim-journal -> view-books

for Dialer:
view-pim-contacts -> view-contacts
call-start -> dialer-call (proabbly we will need something like dialer-call-start and dialer-call-end dialer-call-pause?)
message-new -> send-sms
mail-message -> send-email

**Comment by UriHerrera** [comment]
- [x] view-pim-notes -> view-notes
- [x] view-pim-news -> view-links
- [x] view-pim-journal -> view-books
- [x] pin -> edit-pin

- [x] changed `document-edit` icon
- [x] added `dialer-carrl-start` `dialer-call-end` and `dialer-call-pause`
- [x] added icon as `sms` and `email`
