### ISSUE TITLE
[Icons Wanted] Clocks-related icons

### ISSUE THREAD

**Issue by pontaoski** [Nitrux/luv-icon-theme#209]
I'm developing a new application called Epoka that offers clocks-related functionality using MauiKit. Currently, Lüv is lacking icons related to clock functionality.
Additionally, an application icon that fits in with other Maui apps would be nice.

Breeze-style icons for reference:
Alarm: 
![image](https://user-images.githubusercontent.com/20326855/66512662-6a937f00-eaa7-11e9-9e25-a1b1de2ce3a6.png)
Stopwatch: 
![image](https://user-images.githubusercontent.com/20326855/66512675-6ff0c980-eaa7-11e9-8ae7-3dc54a12bd37.png)
Timer: 
![image](https://user-images.githubusercontent.com/20326855/66512683-754e1400-eaa7-11e9-95e3-cb4c0e083e03.png)
Clock:
![image](https://user-images.githubusercontent.com/20326855/66512726-8b5bd480-eaa7-11e9-9b59-5a3cfe12d365.png)

Thanks in advance <3

**Comment by UriHerrera** [comment]
What is the name of the icons that your application is going to use?

**Comment by Appadeia** [comment]
The application's icon: `epoka`
Clock: `clock`
Stopwatch: `stopwatch`
Timer: `timer`
Alarm: `alarm`

**Comment by UriHerrera** [comment]
Icons added in https://github.com/Nitrux/luv-icon-theme/commit/6f0fb464ebb351328980935516d59292ef17fdcf
