### ISSUE TITLE
[Linux] Visual Studio Code,Pycharm KDE Plasma 5

### ISSUE THREAD

**Issue by rago666** [Nitrux/luv-icon-theme#212]
No icon available for Visual Studio Code or Pycharm.

**Comment by UriHerrera** [comment]
Please follow the guidelines in the README to report icons.

**Comment by UriHerrera** [comment]
I'm closing this according to the [FAQ](https://github.com/Nitrux/luv-icon-theme/wiki/L%C3%BCv-FAQ#creating-new-issues).

> Issues must have all the information listed in the [README](https://github.com/Nitrux/luv-icon-theme/blob/master/README.md#reporting-missing-icons). It won't be fixed if you don't have all the info required for your problem.
