### ISSUE TITLE
"Night Color Control" icon absent

### ISSUE THREAD

**Issue by demoy** [Nitrux/luv-icon-theme#217]
I am using plasma 5.18 and with it there is the built-in ability to control Gamma (similiar to Redshift). Can you add for it?
![Screenshot_20200301_191217](https://user-images.githubusercontent.com/2396524/75637129-61d84c80-5bf2-11ea-92a7-f3fb39644c93.png)

In the KDE System Setting it uses a stock icon but has none in the status area
![Screenshot_20200301_192135](https://user-images.githubusercontent.com/2396524/75637210-e88d2980-5bf2-11ea-9286-807c01ea278a.png)

**Comment by UriHerrera** [comment]
How are you adding the applet to the panel?

**Comment by demoy** [comment]
The applet is in the status area by default but only shows  up during the hours Night Color is set  as active. For me I use my lat and longitude:
![Screenshot_20200302_025443](https://user-images.githubusercontent.com/2396524/75656638-5dcc1f00-5c32-11ea-9356-1444a23c3c8e.png)

I would like to show you what the stock breeze icon looks like but currently tke KDE team messed up somewhere and KDE settings can't change the icon theme (nor window theme) back to the stock breeze. So I would have to delete the icon theme entry from KDEGlobal and restart plasma to get the stock icon to show up: it looks like a light bulb.

**Comment by fleamour** [comment]
Anyone know name of icon? I have similar problem under Numix Circle icon set under openSUSE Tumbleweed KDE.

**Comment by EsauPR** [comment]
I have the same issue and also with the microphone icon. This icon appear when the microphone is used. I'm using the brisa dark theme on KDE.

![all](https://user-images.githubusercontent.com/5316211/87866304-d0ba0600-c945-11ea-9037-62fdf60adbd0.png)
![micro](https://user-images.githubusercontent.com/5316211/87866305-d1529c80-c945-11ea-90d4-69752a30d113.png)
![night_control](https://user-images.githubusercontent.com/5316211/87866306-d1eb3300-c945-11ea-8dd2-63677429fa41.png)

**Comment by UriHerrera** [comment]
> I have the same issue and also with the microphone icon. This icon appear when the microphone is used. I'm using the brisa dark theme on KDE.
> 
> ![all](https://user-images.githubusercontent.com/5316211/87866304-d0ba0600-c945-11ea-9037-62fdf60adbd0.png)
> ![micro](https://user-images.githubusercontent.com/5316211/87866305-d1529c80-c945-11ea-90d4-69752a30d113.png)
> ![night_control](https://user-images.githubusercontent.com/5316211/87866306-d1eb3300-c945-11ea-8dd2-63677429fa41.png)

Please open a separate issue.

**Comment by UriHerrera** [comment]
I've added the icons `redshift-status-on` and `redshift-status-off` to the icon theme solving this issue. However, Plasma uses the `-off` icon in both instances where it's displayed; I think that's wrong, it should use both, but I digress.

Fixed in f11b67d.
