### ISSUE TITLE
Mark releases with tags

### ISSUE THREAD

**Issue by suve** [Nitrux/luv-icon-theme#221]
Many commits (e.g. 81ca567d40eb5c4d3de911b7c41d9a8f1d02b3fd, 4b77e9560da52645d1d19681e0eb08145c746d4f, 598bbc38fb2dde34a3c497b4b6cf5c3ec46dc416) increase the version number in `debian/changelog`. At the same time, none of those are tagged using git tags.

Having new versions marked with git tags would be very useful for downstream packaging.

**Comment by UriHerrera** [comment]
The version number in the Debian package files is not reflective or utilized to version the icon theme assets.

I will add a continuous tag to the releases section.

**Comment by UriHerrera** [comment]
The tag has been active for a while.
