### ISSUE TITLE
Gnome default apps missing

### ISSUE THREAD

**Issue by Gaw18** [Nitrux/luv-icon-theme#229]
Almost all GNOME apps but some that should be changed because they are the main ones.
I made a screenshot Before and after the use of Luv team, only terminal and spotify in the bar was changed
The apps is (in order as in the picture):

- **Firefox-esr**
- **Evolution** (base mail manger of gnome): https://gitlab.gnome.org/GNOME/evolution/
- **Nautilus** (gnome file manager): https://github.com/GNOME/nautilus
- **Tweaks** (gnome tweaks app): https://wiki.gnome.org/Apps/Tweaks
- **Telegram**
- **Visual Studio Code** (by Microsoft)
- **Microsoft Teams**
- **obs-studio**: (https://github.com/obsproject/obs-studio)
- **owncloud client**

_**Before**_:

![Screenshot from 2020-11-20 11-48-07](https://user-images.githubusercontent.com/61871789/99793764-6a2e3a00-2b29-11eb-8976-3029f6cba58e.png)

_**After**_:

![Screenshot from 2020-11-20 11-47-45](https://user-images.githubusercontent.com/61871789/99794644-c6de2480-2b2a-11eb-95a3-98e1d8fb9215.png)

DE:Gnome 3.30.2

**Comment by UriHerrera** [comment]
I'm closing this according to the [FAQ](https://github.com/Nitrux/luv-icon-theme/wiki/L%C3%BCv-FAQ#creating-new-issues).

> Issues must have all the information listed in the [README](https://github.com/Nitrux/luv-icon-theme/blob/master/README.md). It won't be fixed if you don't have all the info required for your problem.
