### ISSUE TITLE
transmission icon missing

### ISSUE THREAD

**Issue by pawanyadav** [Nitrux/luv-icon-theme#234]
transmission icon (app and systemtray) is missing (kde)

**Comment by UriHerrera** [comment]
I'm closing this according to the [FAQ](https://github.com/Nitrux/luv-icon-theme/wiki/L%C3%BCv-FAQ#creating-new-issues).

> Issues must have all the information listed in the [README](https://github.com/Nitrux/luv-icon-theme/blob/master/README.md#reporting-missing-icons). It won't be fixed if you don't have all the info required for your problem.
