### ISSUE TITLE
Add icons to Nitrux Calamares QML branding

### ISSUE THREAD

**Issue by milohr** [Nitrux/luv-icon-theme#235]
Icon needed are:

- cala-qml-welcome
- cala-qml-language
- cala-qml-region
- cala-qml-timezone
- cala-qml-keyboard-model
- cala-qml-keyboard-layout 
- cala-qml-keyboard-layout-variant 
- cala-qml-user
- cala-qml-partition
- cala-qml-look-and-feel
- cala-qml-finished

**Comment by UriHerrera** [comment]
Icons added
