### ISSUE TITLE
Missing icons for Maui Apps WIP

### ISSUE THREAD

**Issue by milohr** [Nitrux/luv-icon-theme#236]
to be completed:

General:

- view-hidden
- dialog-scripts (alias to the terminal icon as an action)

Pix:

- gps (pin)
- checkmar
- dialog-cancel
- transfrom-crop
- transfrom-rotate
- object-flip-horizontal
- object-flip-vertical
- 

Index:

Nota:

- view-readermode-active
- view-readermode

NX SC:
- package
- rating
- download
- license

MauiKit Core:

- license (actions/about dialog)
- code-context  (actions/about dialog)
- plugins (actions/about dialog)

**Comment by UriHerrera** [comment]
Added icons in 514ac05
