### ISSUE TITLE
Some icons broken

### ISSUE THREAD

**Issue by unc926** [Nitrux/luv-icon-theme#246]
**Describe the bug**
I'm not sure project is continuing, However, report may help fix in the future.
Some **Action** icons look broken

**Expected behavior**
It is clearly seen on Github that is some icons corrupted.

**Screenshots**
![Screenshot_20231223_220710](https://github.com/Nitrux/luv-icon-theme/assets/30185386/fc4339b8-3e1c-452f-ac85-3b9d167b1f65)
![Screenshot_20231223_220646](https://github.com/Nitrux/luv-icon-theme/assets/30185386/dd74dde4-4264-4184-97af-8cfbcd767350)
![Screenshot_20231223_220842](https://github.com/Nitrux/luv-icon-theme/assets/30185386/5f614506-6d88-4720-b26b-566b94cc9154)

Moreover. Steam icon has a translucent square background

![Screenshot_20231223_222903](https://github.com/Nitrux/luv-icon-theme/assets/30185386/c6259ac4-4244-4c2f-bf8d-15275c074d1b)

**Comment by UriHerrera** [comment]
The action icons you mentioned are not symlinks and are not broken; they had a rendering issue of some sort.

Fixed in https://github.com/Nitrux/luv-icon-theme/commit/cd15ec28e131d29fc1c1afaa289dc9a70d786428

**Comment by UriHerrera** [comment]
The action icons you mentioned had a rendering issue of some sort.

Fixed in https://github.com/Nitrux/luv-icon-theme/commit/cd15ec28e131d29fc1c1afaa289dc9a70d786428
